import {
	FaGithub,
	FaInstagram,
	FaLinkedin,
	FaPinterest,
	FaRegBookmark,
	FaRegUser,
	FaSteam,
	FaTwitch,
	FaApple,
	FaHandshake,
	FaLaptopCode,
	FaCode,
	FaShieldAlt,
	FaServer,
	FaMobileAlt,
	FaPaintBrush,
	FaCloud,
} from 'react-icons/fa';
import { HiServerStack, HiComputerDesktop, HiExclamationTriangle, HiCheckCircle, HiBolt, HiShieldCheck, HiClock, HiCodeBracketSquare } from 'react-icons/hi2';
import { IoGridOutline } from 'react-icons/io5';
import { MdOutlineCloudDone } from 'react-icons/md';
import type { Project } from '../types';
import type { Service } from '../types';


export const personalInfo = {
	name: 'Devmike117',
	age: null,
	location: 'null',
	occupation: 'Full-Stack Developer & Traveling Tech Enthusiast',
	overview:
		'Egresado de Ing. en Sistemas Computacionales. Trabajo en desarrollo web, software y temas de ciberseguridad.',
	hobbies: [
		'Hobbies:',
		// Y que viva the neighbourhood jaja ok no, bueno si pero no lo pongo :D
	],
	otherLinks: [
		{
			id: 1,
			name: 'Mi Portfolio',
			url: 'https://devmikeportfolio.netlify.app/',

		},
	],
	song: {
    title: 'Stuck with Me',
    artist: 'The Neighbourhood',
    url: 'https://raw.githubusercontent.com/Devmike117/music1/main/Stuck%20with%20Me%20-%20The%20Neighbourhood.mp3', 
  },
	socialLinks: [
		{
			id: 1,
			name: 'Instagram',
			url: 'https://www.instagram.com/devmike117/',
			icon: <FaInstagram size={30} />,
		},
		{
			id: 2,
			name: 'GitHub',
			url: 'https://github.com/Devmike117',
			icon: <FaGithub size={30} />,
		},
		{
			id: 3,
			name: 'LinkedIn',
			url: 'https://www.linkedin.com/in/miguelgabrielhndz/',
			icon: <FaLinkedin size={30} />,
		},
		{
			id: 4,
			name: 'Devmike tools',
			url: 'https://tools.devmike117.com/',
			icon: <FaLaptopCode size={30} />,
		},
		{
			id: 5,
			name: 'Steam',
			url: 'https://steamcommunity.com/id/mikedarkness',
			icon: <FaSteam size={30} />,	
		},
		{
			id: 6,
			name: 'Twitch',
			url: 'https://www.twitch.tv/devmike117',
			icon: <FaTwitch size={30} />,
			},
	],
	photoSrc: '/foto.webp',
};

export const tabs = [
	{
		id: 1,
		name: 'Proyectos',
		icon: IoGridOutline,
	},
	{
		id: 2,
		name: 'Experiencia',
		icon: FaRegBookmark,
	},
	{
		id: 3,
		name: 'Habilidades',
		icon: FaRegUser,
	},
	{
		id: 4,
		name: 'servicios',
		icon: FaHandshake,
	},
];

export const projects: Project[] = [
	{
		id: 0,
		name: 'Devmike tools',
		description:
			'Es una plataforma web que ofrece una variedad de herramientas gratuitas para desarrolladores y estudiantes. Diseñada para mejorar la productividad y facilitar el trabajo.',
		technologies: [
			// Frontend y Frameworks
			'React',
			'React DOM',
			'React Router DOM',
			'TypeScript',
			'Vite',
			// Estilos y UI
			'Tailwind CSS',
			'PostCSS',
			'Autoprefixer',
			'React Icons',
			// Animaciones
			'Framer Motion',
			// Procesamiento de imágenes y multimedia
			'@ffmpeg/ffmpeg',
			'@ffmpeg/util',
			'jszip',
			'@imgly/background-removal',
			'heic2any',
			'html2canvas',
			'pdf-lib',
			'pdfjs-dist',
			'tesseract.js (OCR)',
			'cloudconvert',
			// Mapas y geolocalización
			'leaflet',
			'react-leaflet',
			'@types/leaflet',
			// Validaciones y utilidades
			'libphonenumber-js',
			'APIS propias',
			'mammoth (Word a HTML)',
			'qrcode',
			'qr-code-styling',
			'dotenv',
			'form-data',
			'formidable',
			'multer',
			'node-fetch',
			// Diagramas y visualización
			'mermaid',
			// Backend/API
			'express',
			'@sparticuz/chromium',
			'playwright-core',
			// Autenticación y servicios
			'firebase',
			// Herramientas de desarrollo
			'eslint',
			'@eslint/js',
			'eslint-plugin-react-hooks',
			'Proxy propio',
			'eslint-plugin-react-refresh',
			'@types/node',
			'@types/react',
			'@types/react-dom',
			'@types/qrcode',
			'typescript-eslint',

		],
		projectUrl: 'https://tools.devmike117.com/',
		imageSrc: [
				'/1tool.devmike117.webp',
				'/2tool.devmike117.webp',
				'/3tool.devmike117.webp',
				'/4tool.devmike117.webp',
				'/5tool.devmike117.webp',
			],		
	},
	{
		id: 1,
		name: 'Plataforma web para restaurante',
		description:
			'Plataforma web moderna y responsiva con sistema de pedidos en línea, reservas, integración de pagos con Stripe, dashboard administrativo con analytics, generación de recibos PDF automáticos y notificaciones por email.',
		technologies: [
			'React',
			'TypeScript',
			'Vite',
			'shadcn/ui',
			'Tailwind CSS',
			'Framer Motion',
			'React Router',
			'Context API',
			'TanStack Query',
			'Node.js',
			'Express',
			'CORS',
			'MongoDB',
			'PostgreSQL',
			'Axios',
			'EmailJS',
			'Stripe API',
			'Chart.js',
			'PDFKit',
		],
		projectUrl: 'https://sistema-restaurante-4wvy.vercel.app/',
		budget: 'Proyecto realizado por: $4,722 USD o $85,000 MXN (sistema de pedidos, reservas, integración de pagos y dashboard administrativo). Para requerimientos adicionales o personalizaciones específicas, el costo aumenta o disminuye según el alcance solicitado.',
		imageSrc: 'https://raw.githubusercontent.com/Devmike117/Devmike117/refs/heads/main/assets/Systemrestaurant.webp',
	},
	{
		id: 2,
		name: 'Devmike downloader',
		description:
			'Es una aplicación de escritorio que permite descargar videos y audios de múltiples plataformas populares: YouTube, Facebook (videos públicos), X, TikTok, Instagram (reels, posts), Twitch y SoundCloud.',
		technologies: [
			'Python',
			'yt-dlp',
			'ffmpeg',
			'Tkinter',
		],
		projectUrl: 'https://tools.devmike117.com/appdownload',
		githubUrl: 'https://github.com/Devmike117/devmike-downloader',
		imageSrc: [
			'/devmike_banner_v3.svg',
			'/devmikedownloader.webp',

		],
		notes: '• Si necesitas instalar ffmpeg, la app te mostrará un botón para descargarlo.\n\n• El ejecutable está firmado digitalmente, pero con un certificado autofirmado.\n\n• La aplicación es completamente gratuita y de código abierto.',
	},
	{
		id: 3,
		name: 'Devmike117 Store',
		description:
			'Devmike117 Store es una plataforma web que combina tienda de productos digitales (licencias de juegos, software, consoles) con servicios técnicos profesionales (desarrollo web, reparación de equipos, recuperación de datos).',
		technologies: [
			'Vite 7',
			'React 19',
			'TypeScript',
			'Tailwind CSS 3',
			'React Router DOM 7',
			'Framer Motion',
			'React Icons',
			'Supabase',
			'Supabase Auth',
			'PostgreSQL',
			'Axios',
			'Stripe',
			'Apple Pay',
			'Google Pay',
			'@stripe/react-stripe-js',
			'@stripe/stripe-js',
			'Google Pay API',
			'Radix UI',
			'Class Variance Authority (CVA)',
			'Tailwind Merge',
			'clsx',
			'jsPDF',
			'jspdf-autotable',
		],
		projectUrl: 'https://devmike117store.vercel.app/',
		githubUrl: 'https://github.com/Devmike117/Headless-Store',
		imageSrc: '/Project02.png',
	},
	{
		id: 4,
		name: 'Quitafondo',
		description:
			'Aplicación de escritorio que elimina fondos de imágenes automáticamente y sin conexión, usando redes neuronales. Ofrece edición manual, compatibilidad con múltiples formatos y preserva la calidad sin subir archivos a terceros.',
		technologies: [
			'Python',
			'tkinter',
			'rembg',
			'Pillow',
			'pyinstaller',
		],
		projectUrl: 'https://github.com/Devmike117/eliminar-fondo-de-imagenes/releases/tag/vv1.0',
		githubUrl: 'https://github.com/Devmike117/eliminar-fondo-de-imagenes',
		imageSrc: '/project2.jpg',
	},
	{
		id: 5,
		name: 'Verificador de correos electrónicos',
		description:
			'Herramienta de escritorio en Python que audita direcciones de correo en tiempo real. Evalúa sintaxis, servidores, autenticación y posibles intentos de phishing, todo de forma local y sin comprometer la privacidad del usuario.',
		technologies: [
			'Python',
			'tkinter',
			'dns.resolver',
			're',
			'socket',
			'smtplib',
			'pyinstaller',
		],
		projectUrl: 'https://github.com/Devmike117/verificar-correos-electronicos/releases/tag/new',
		githubUrl: 'https://github.com/Devmike117/verificar-correos-electronicos',
		imageSrc: '/project3.jpg',
	},
	{
		id: 6,
		name: 'Sistema de Cifrado Web para PDFs',
		description:
			'Sistema que permite cifrar archivos PDF utilizando algoritmos como ECC, RSA, AES y ChaCha20. Ideal para proteger documentos sensibles en contextos educativos, profesionales o personales.',
		technologies: [
			'Python',
			'Flask',
			'HTML5',
			'CSS3',
			'tkinter',
			'PyCryptodome',
			'cryptography',
			'Scripts personalizados',
		],

		projectUrl: '#',
		githubUrl: 'https://github.com/Devmike117/Sistema-de-Cifrado-Web-para-PDFs',
		imageSrc: '/project4.png',
	},
	{
		id: 7,
		name: 'Modelo de Detección de Rostros',
		description:
			'Identifica rostros humanos en tiempo real y en imágenes estáticas usando algoritmos Haar Cascade y redes neuronales. Funciona localmente y es útil para pruebas biométricas básicas y sistemas de autenticación.',
		technologies: [
			'Python',
			'OpenCV',
			'tkinter',
			'CNN',
			'CMake',
			'HTML5',
			'CSS3',
			'JavaScript',
		],
		projectUrl: '#',
		githubUrl: 'https://github.com/Devmike117/modelo-deteccion-de-rostros',
		imageSrc: '/project5.png',
	},
	{
		id: 8,
		name: 'Generador de Códigos QR',
		description:
			'Herramienta que permite crear códigos QR personalizados en segundos, a partir de texto, enlaces o datos de contacto. Funciona sin conexión a internet y es ideal para compartir información de forma rápida y moderna.',
		technologies: [
			'Python',
			'tkinter',
			'qrcode',
			'Pillow',
			'pyinstaller',
		],
		projectUrl: 'https://github.com/Devmike117/Generador-codigos-QR/releases/tag/VV1.0',
		githubUrl: 'https://github.com/Devmike117/Generador-codigos-QR',
		imageSrc: '/project6.png',
	},
];

export const experience = [
	{
		id: 0,
		position: 'Desarrollador Full-Stack (Freelance)',
		timeRange: 'Nov 2025 - Dic 2025',
		companyName: 'Cadena de restaurante.',
		companyLocation: 'Toluca de Lerdo, México',
		description:
			'Desarrollo de una plataforma web que permite realizar pedidos en línea, diferentes métodos de pago, gestionar reservas y recibir confirmaciones automáticas por correo electrónico.\n\n' +
			'• Interfaz amigable para usuarios y administradores, facilitando la navegación y el manejo de pedidos.\n\n' +
			'• Integración de pasarelas de pago seguras para garantizar transacciones confiables.\n\n' +
			'• Panel administrativo para monitorear pedidos, gestionar menús y analizar estadísticas de ventas. \n\n' +
			'• Exportación de datos a formatos CSV y PDF para facilitar la contabilidad y el análisis de ventas. \n\n' +
			'• Recibos digitales generados automáticamente y enviados por correo electrónico tras cada compra.',

		technologiesUsed: [
			'React',
			'TypeScript',
			'Vite',
			'shadcn/ui',
			'Tailwind CSS',
			'Framer Motion',
			'React Router',
			'Context API',
			'TanStack Query',
			'Node.js',
			'Express',
			'CORS',
			'MongoDB',
			'PostgreSQL',
			'Axios',
			'EmailJS',
			'Stripe API',
			'Chart.js',
			'PDFKit',
		],
	},
	{
		id: 1,
		position: 'Front-end developer',
		timeRange: 'Sep 2025 – Ene 2026',
		companyName: 'Gobierno de México. Centro de comando y control c2.',
		companyLocation: 'México',
		description:
			'Residencia profesional donde se desarrolló un sistema de arrestos administrativos para centros de comando y control.\n\n' +
			'• El sistema permite registrar, buscar y gestionar personas arrestadas mediante biometría facial y escaneo de huellas, generando plantillas cifradas que evitan duplicidades.\n\n' +
			'• Su arquitectura elimina registros manuales, reduce errores y agiliza decisiones operativas.\n\n' +
			'• Detecta reincidencias con el algoritmo de reconocimiento facial, actualiza historiales y genera reportes PDF con firma digital y código QR único.\n\n' +
			'• Dashboard analítico para visualizar estadísticas en tiempo real y control de acceso para administradores.\n\n' +
			'• Operación vía intranet, bajo estándares de seguridad y privacidad, cumpliendo con normativas nacionales e internacionales en protección de datos personales y biométricos.',

		technologiesUsed: [
			'React',
			'Chart.js',
			'react-chartjs-2',
			'Axios JS',
			'QRCode.react',
			'Node.js',
			'Express',
			'PostgreSQL',
			'pgAdmin',
			'Multer',
			'PDFKit',
			'bcrypt',
			'CORS',
			'FastAPI',
			'DeepFace',
			'TensorFlow / Keras',
			'OpenCV',
			'NumPy',
			'Docker',
			'Docker Compose',
			'Git',
			'GitHub',
			'Python',
			'tailwind css',
			'JavaScript',
			'ISO/IEC 27001',
			'ISO/IEC 27701',
			'ISO/IEC 29100',
			'BD de Estados de la República Mexicana propia en formato .JSON',
			'Ley Federal de Protección de Datos Personales (México)',
		],
	},
	{
		id: 2,
		position: 'Student Assembly Developer',
		timeRange: 'Jul 2022 – Jul 2024',
		companyName: 'Microsoft.',
		companyLocation: 'Remoto',
		description:
			'Participación en el programa Student Assembly de Microsoft, donde accedi a las últimas tecnologías y herramientas para desarrollar soluciones innovadoras. Trabajé en proyectos colaborativos, mejorando mis habilidades técnicas y de trabajo en equipo en un entorno profesional.',
		technologiesUsed: ['Azure', 'Visual Studio', 'GitHub', 'GitHub Actions'],
	},
	{
		id: 3,
		position: 'Developer videogame',
		timeRange: '2022 – 2022',
		companyName: 'Ugame Studio.',
		companyLocation: 'Online',
		description:
			'Desarrollo de un videojuego estilo Doom con mecánicas de roguelike y survival horror en Unity. Implementación de sistemas de combate, generación procedural de niveles y gestión de recursos para crear una experiencia inmersiva y desafiante. Como parte de acceso previo a su tecnología',
		technologiesUsed: ['Unity', 'C#', 'Visual Studio', 'GitHub'],
	},
];

export const skills = [
	{
		id: 1,
		imageSrc: '/react.png',
		technologyName: 'React',
		level: 'Intermedio',
		context: 'Frontend',
		bgColor: '#E1F5FE',
		borderColor: '#81D4FA',
	},
	{
		id: 2,
		imageSrc: '/nextjs.png',
		technologyName: 'Next.js',
		level: 'Básico',
		context: 'Full-Stack',
		bgColor: '#F5F5F5',
		borderColor: '#BDBDBD',
	},
	{
		id: 3,
		imageSrc: '/nodejs.png',
		technologyName: 'Node.js',
		level: 'Intermedio',
		context: 'Backend',
		bgColor: '#E8F5E8',
		borderColor: '#81C784',
	},
	{
		id: 4,
		imageSrc: '/nestjs.png',
		technologyName: 'NestJS',
		level: 'Intermedio',
		context: 'Backend',
		bgColor: '#FCE4EC',
		borderColor: '#F48FB1',
	},
	{
		id: 5,
		imageSrc: '/gsap.png',
		technologyName: 'GSAP',
		level: 'Intermedio',
		context: 'Animations',
		bgColor: '#F1F8E9',
		borderColor: '#AED581',
	},
	{
		id: 6,
		imageSrc: '/tailwindcss.png',
		technologyName: 'Tailwind CSS',
		level: 'Avanzado',
		context: 'UI/UX',
		bgColor: '#E0F7FA',
		borderColor: '#80DEEA',
	},
	{
		id: 7,
		imageSrc: '/typescript.png',
		technologyName: 'TypeScript',
		level: 'Avanzado',
		context: 'Language',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 8,
		imageSrc: '/javascript.png',
		technologyName: 'JavaScript',
		level: 'Avanzado',
		context: 'Language',
		bgColor: '#FFFDE7',
		borderColor: '#FFF176',
	},
	{
		id: 9,
		imageSrc: '/python.png',
		technologyName: 'Python',
		level: 'Intermedio',
		context: 'Backend',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 10,
		imageSrc: '/flutter.png',
		technologyName: 'Flutter',
		level: 'Intermedio',
		context: 'Mobile',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 11,
		imageSrc: '/graphql.png',
		technologyName: 'GraphQL',
		level: 'Intermedio',
		context: 'API',
		bgColor: '#FCE4EC',
		borderColor: '#F8BBD9',
	},
	{
		id: 12,
		imageSrc: '/docker.png',
		technologyName: 'Docker',
		level: 'Intermedio',
		context: 'DevOps',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 13,
		imageSrc: '/aws.png',
		technologyName: 'AWS',
		level: 'Intermedio',
		context: 'Cloud',
		bgColor: '#FFF8E1',
		borderColor: '#FFCC02',
	},
	{
		id: 14,
		imageSrc: '/firebase.png',
		technologyName: 'Firebase',
		level: 'Básico',
		context: 'Backend',
		bgColor: '#FFF8E1',
		borderColor: '#FFD54F',
	},
	{
		id: 15,
		imageSrc: '/googlecloud.png',
		technologyName: 'Google Cloud',
		level: 'Básico',
		context: 'Cloud',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 16,
		imageSrc: '/mongodb.png',
		technologyName: 'MongoDB',
		level: 'Intermedio',
		context: 'Database',
		bgColor: '#E8F5E8',
		borderColor: '#A5D6A7',
	},
	{
		id: 17,
		imageSrc: '/postgresql.png',
		technologyName: 'PostgreSQL',
		level: 'Intermedio',
		context: 'Database',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 18,
		imageSrc: '/unity.webp',
		technologyName: 'Unity',
		level: 'Intermedio',
		context: 'Game Dev',
		bgColor: '#FAFAFA',
		borderColor: '#E0E0E0',
	},
	{
		id: 19,
		imageSrc: '/storybook.png',
		technologyName: 'Storybook',
		level: 'Básico',
		context: 'UI Tools',
		bgColor: '#FCE4EC',
		borderColor: '#F8BBD9',
	},
	{
		id: 20,
		imageSrc: '/fastapi.png',
		technologyName: 'FastAPI',
		level: 'Intermedio',
		context: 'Backend',
		bgColor: '#E0F2F1',
		borderColor: '#80CBC4',
	},
	{
		id: 21,
		imageSrc: '/elasticsearch.png',
		technologyName: 'Elasticsearch',
		level: 'Básico',
		context: 'Search',
		bgColor: '#E0F7FA',
		borderColor: '#80DEEA',
	},
	{
		id: 22,
		imageSrc: '/netlify.png',
		technologyName: 'Netlify',
		level: 'Avanzado',
		context: 'Deployment',
		bgColor: '#E8F5E8',
		borderColor: '#81C784',
	},
	{
		id : 23,
		imageSrc: '/git.png',
		technologyName: 'Git',
		level: 'Avanzado',
		context: 'version control',
		bgColor: '#F3E5F5',
		borderColor: '#E1BEE7',
	},
	{
		id: 24,
		imageSrc: '/githubb.png',
		technologyName: 'GitHub',
		level: 'Avanzado',
		context: 'version control',
		bgColor: '#E8E8E8',
		borderColor: '#B0B0B0',
	}
];

export const services: Service[] = [
	{
		id: 1,
		name: 'Actualización macOS',
		icon: FaApple,
		price: 'Desde $599 MXN',
		description:
			'Actualiza tu Mac sin soporte oficial de Apple a versiones más recientes de macOS. Extendemos la vida útil de tu equipo con métodos especializados.',
		features: [
			{ title: 'Evaluación de compatibilidad', description: 'Verificamos si tu Mac puede ejecutar la versión deseada' },
			{ title: 'Respaldo de datos', description: 'Verificamos que tengas respaldo antes de proceder' },
			{ title: 'Instalación de macOS', description: 'Instalamos la versión más reciente compatible con tu Mac' },
			{ title: 'Verificación de hardware', description: 'Comprobamos que WiFi, Bluetooth, gráficos y audio funcionen' },
		],
		process: [
			{ title: 'Evaluación inicial', description: 'Verificamos modelo, especificaciones y compatibilidad de tu Mac' },
			{ title: 'Respaldo de datos', description: 'Confirmamos que tengas respaldo o te ayudamos a crearlo' },
			{ title: 'Instalación', description: 'Proceso de instalación de la nueva versión de macOS (2-4 horas)' },
			{ title: 'Verificación y entrega', description: 'Probamos que todo funcione y te explicamos los cambios' },
		],
		warnings: [
			'Respaldo obligatorio: debes tener una copia de seguridad completa (Time Machine recomendado)',
			'No es oficial: esta actualización no está soportada por Apple y se hace bajo tu responsabilidad',
			'Apple no brindará soporte para Macs con sistema no oficial',
		],
		estimatedTime: '3 a 5 horas aproximadamente',
	},
	{
	id: 2,
	name: 'Desarrollo Web',
	icon: HiCodeBracketSquare,
	price: 'Desde $7,999 MXN',
	description:
		'Tu negocio en línea, en días, no meses. Sitios rápidos, modernos y diseñados para convertir visitantes en clientes.',
	features: [
		{ title: '100% Responsivo', description: 'Perfecto en cualquier pantalla' },
		{ title: 'Súper rápido', description: 'Tecnología JAMstack, no hosting lento' },
		{ title: 'Dominio incluido', description: '.com o .mx por 1 año' },
		{ title: 'SSL & SEO', description: 'Seguro y listo para Google' },
	],
	plans: [
		{
			name: 'Básico',
			price: '$7,999 MXN',
			tagline: 'Para arrancar',
			items: [
				'5 secciones',
				'Formulario de contacto',
				'Dominio incluido 1 año',
			],
		},
		{
			name: 'Profesional',
			price: '$14,999 MXN',
			tagline: 'Más popular',
			recommended: true,
			items: [
				'10 secciones',
				'Galería profesional',
				'SEO avanzado + Analytics',
			],
		},
		{
			name: 'E-commerce',
			price: '$39,999 MXN',
			tagline: 'Vende en línea',
			items: [
				'Tienda completa',
				'50 productos',
				'Pagos + panel admin',
			],
		},
	],
	estimatedTime: '1 a 5 semanas según el plan',
	},
	{
		id: 3,
		name: 'Ciberseguridad',
		icon: FaShieldAlt,
		price: 'Cotización según alcance',
		description: 'Auditorías, cifrado de documentos y hardening de sistemas.',
	},
	{
	id: 4,
	name: 'Mantenimiento PC',
	icon: HiComputerDesktop,
	price: 'Desde $299 MXN',
	description:
		'Mantén tu computadora funcionando como nueva. Limpieza física y digital, optimización del sistema y actualizaciones para un rendimiento óptimo.',
	features: [
		{ title: 'Limpieza física completa', description: 'Eliminación de polvo del ventilador, disipador y componentes internos' },
		{ title: 'Cambio de pasta térmica', description: 'Aplicación de pasta térmica nueva para mejor disipación de calor' },
		{ title: 'Optimización del sistema', description: 'Eliminación de archivos temporales y programas innecesarios' },
		{ title: 'Escaneo de malware', description: 'Detección de virus y programas maliciosos básicos' },
		{ title: 'Verificación de actualizaciones', description: 'Revisión de actualizaciones pendientes del sistema' },
		{ title: 'Prueba de hardware', description: 'Verificación del estado general de componentes' },
	],
	whenToUse: [
		'La computadora está muy lenta',
		'Se sobrecalienta o hace ruidos extraños',
		'Tarda mucho en encender',
		'Se traba o congela frecuentemente',
		'Los programas tardan en abrir',
	],
	benefits: [
		{ title: 'Mayor velocidad', description: 'Tu PC funcionará más rápido y eficiente', icon: HiBolt },
		{ title: 'Más seguridad', description: 'Protección contra virus y malware', icon: HiShieldCheck },
		{ title: 'Mayor vida útil', description: 'Extiende la duración de tu equipo', icon: HiClock },
	],
	estimatedTime: 'Aproximadamente 1 a 2 horas, dependiendo del estado del equipo',
	},
{
	id: 5,
	name: 'Instalación de SO',
	icon: HiServerStack,
	price: 'Desde $349 MXN',
	description:
		'Tu PC como nueva en horas. Windows o Linux, con drivers, actualizaciones y programas esenciales listos para usar.',
	features: [
		{ title: 'Instalación limpia', description: 'Sistema desde cero, sin basura' },
		{ title: 'Drivers al día', description: 'Todo funcionando de inmediato' },
		{ title: 'Listo para usar', description: 'Navegador, antivirus y esenciales' },
	],
	plans: [
		{
			name: 'Windows',
			price: '$349 - $499 MXN',
			tagline: 'Win 11, 10, 8.1 o 7',
			items: [
				'Drivers y activación',
				'Actualizaciones completas',
				'Configuración inicial',
			],
		},
		{
			name: 'Linux',
			price: '$399 MXN',
			tagline: 'Ubuntu, Mint, Fedora y más',
			items: [
				'Instalación + drivers',
				'Capacitación básica',
				'Ideal para desarrollo',
			],
		},
		{
			name: 'Dual Boot',
			price: '$699 MXN',
			tagline: 'Windows + Linux, elige al iniciar',
			recommended: true,
			items: [
				'Particionado seguro',
				'Ambos sistemas configurados',
				'Trabajo y desarrollo en un equipo',
			],
		},
	],
	warnings: [
		'La instalación formatea el disco y elimina todos los archivos — te ayudamos a respaldar antes',
	],
	estimatedTime: '2 a 4 horas aproximadamente',
},
{
	id: 6,
	name: 'Recuperación de Datos',
	icon: MdOutlineCloudDone,
	price: 'Diagnóstico gratis',
	description:
		'¿Borraste o perdiste archivos importantes? Los recuperamos de discos, USB y SD. Solo cobramos si lo logramos.',
	features: [
		{ title: 'Diagnóstico gratuito', description: 'Sin costo, sin compromiso' },
		{ title: 'Cualquier dispositivo', description: 'HDD, SSD, USB, SD y más' },
		{ title: 'Solo pagas si recuperamos', description: '100% confidencial' },
	],
	plans: [
		{
			name: 'Básica',
			price: '$799 MXN',
			tagline: 'USB, SD, archivos recientes',
			items: [
				'Archivos eliminados',
				'Formateo simple',
			],
		},
		{
			name: 'Intermedia',
			price: '$1,499 MXN',
			tagline: 'Discos con fallos lógicos',
			items: [
				'HDD / SSD',
				'Particiones dañadas',
			],
		},
		{
			name: 'Avanzada',
			price: 'Desde $2,499 MXN',
			tagline: 'Daño físico o casos complejos',
			items: [
				'Disco no reconocido',
				'Requiere sala limpia',
			],
		},
	],
	warnings: [
		'Deja de usar el dispositivo de inmediato — seguir usándolo reduce las posibilidades de recuperar tus datos',
	],
	estimatedTime: 'Diagnóstico en 24-48 hrs, recuperación según complejidad',
	},
];